const PDFDocument = require("pdfkit");

const generateCertificate = (data, res) => {
  const doc = new PDFDocument();

  res.setHeader(
    "Content-Type",
    "application/pdf"
  );

  res.setHeader(
    "Content-Disposition",
    `attachment; filename=certificate-${data.certificateId}.pdf`
  );

  doc.pipe(res);

  // ================= HEADER =================
  doc.fontSize(24).text("🏫 CERTIFICATE OF ACHIEVEMENT", {
    align: "center",
  });

  doc.moveDown();

  // ================= BODY =================
  doc.fontSize(16).text(`Certificate ID: ${data.certificateId}`);
  doc.text(`Student: ${data.studentName}`);
  doc.text(`School: ${data.schoolName}`);
  doc.text(`Exam: ${data.examTitle}`);

  doc.moveDown();

  doc.fontSize(18).text(
    `Score: ${data.score}/${data.total}`,
    { align: "center" }
  );

  doc.text(`Grade: ${data.grade}`, {
    align: "center",
  });

  doc.moveDown();

  doc.fontSize(12).text(
    `Issued At: ${new Date().toLocaleString()}`,
    { align: "center" }
  );

  // ================= FOOTER =================
  doc.moveDown(2);
  doc.fontSize(10).text(
    "This certificate is digitally generated by CBT SaaS System",
    { align: "center" }
  );

  doc.end();
};

module.exports = generateCertificate;